FROM alpine:3.17.2

ARG REPO="bash-append"
ARG SCRIPT_FILE="append.sh"
ARG WORKSHOP_NAME="workshop"

RUN apk add --no-cache git \
    && git clone --depth 1 --branch main https://github.com/zamzoki/${REPO}.git \
    && mv /${REPO}/${SCRIPT_FILE} . \
    && chmod 755 /${SCRIPT_FILE} \
    && rm -r ${REPO} \
    && apk del git \
    && mkdir ${WORKSHOP_NAME}

ENTRYPOINT [ "/bin/sh", "append.sh" ]